// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTechnique.Data;

namespace TestTechnique.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200312161129_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestTechnique.Models.Link", b =>
                {
                    b.Property<string>("ShortLink")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatorEmail")
                        .IsRequired();

                    b.Property<string>("OriginalLink");

                    b.HasKey("ShortLink");

                    b.HasIndex("CreatorEmail");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("TestTechnique.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pwd");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestTechnique.Models.Link", b =>
                {
                    b.HasOne("TestTechnique.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorEmail")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
